Repository summerhoax/summerhoax.github.io, pull requests merged in 2019-05, with the labels that each got.

#27 IWA-Hosting
  index.html
Labels: Awaiting Vault Card, Priority: Medium, Requesting Evidence

#28 PingNode
  index.html
Labels: Requesting Evidence, Status: Needs Review

#33 Create 404.html
  404.html
Labels: Priority: Medium, Status: In Progress, Status: Needs Review, enhancement

#32 Request for Removal: Webrex Hosting
  index.html
  vault/assets/webrex/logo.png
  vault/index.html
Labels: Priority: Medium, Status: Needs Review

#36 Meta
  index.html
Labels: Priority: Low, Status: In Progress, Status: Needs Review

#40 IMPROVED** Actually Good Dark Theme
  assets/main.css
Labels: Priority: Medium, enhancement

#38 Revert "Request for Removal: Webrex Hosting"
  index.html
  vault/assets/webrex/logo.png
  vault/index.html
Labels: Priority: Low, Status: In Progress

#45 Fixes Navbar (#39)
  404.html
  index.html
  vault/icx/index.html
  vault/index.html
  vault/prout/index.html
  vault/template/index.html
Labels: Priority: High, Status: Code Needs Review, Status: In Progress

#51 Adds Venom Hosting
  index.html
Labels: Status: Code Needs Review, Status: Needs Community Review
